### PR TITLE
SGS 183

### PR DESCRIPTION
**Pull request by jayaajay**
This exposes max_duration as a configuration option. If not set, it defaults to 30 days in seconds.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
@jayaajay - please see https://github.com/datalogistics/ibp_server/pull/21#commitcomment-13991198

**Comment by jayaajay** [comment]
@PerilousApricot  I have fixed all the review comments and tested it. You can merge this branch if there are no other review comments.

**Comment by PerilousApricot** [comment]
Looks great! If you can smash the commits on this branch, I'll pull it in.

**Comment by jayaajay** [comment]
Done!

**Comment by PerilousApricot** [comment]
Cheers!

**Pull request merged**
