### PR TITLE
LevelDB build fixes

### PR DESCRIPTION
**Pull request by PerilousApricot**
Had LevelDB on my mind, so I poked at this for a bit.

First, I cleaned up the CMake bits to make things build more sensibly (still off by default, `cmake -D _ENABLE_LEVELDB=1` will try and get things going). I also snuck in a small change to silence some compiler warnings.

Second, I'm working on fine-grained runtime profiling to see where things can be smoothed out. I suspect a non-trivial amount of time will be spent within LevelDB itself, so I'd like to instrument it as well. There's a bit of an impedance mismatch between the C++ LevelDB implementation, the C wrapper API, and what we're looking to receive. If something pathological turns up, perhaps it can be fixed and sent upstream.

Unfortunately, git submodules make that a pretty big pain. The 2nd change is to swap the leveldb submodule out with a git subtree (squashed to keep from blowing up repo with all the history).

Build & completes properly on both OSX (10.A) & Centos6 with and without enabling leveldb.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
@disprosium8 Mind taking a look at your convenience?

**Comment by PerilousApricot** [comment]
@disprosium8 ping here

**Comment by disprosium8** [comment]
I just build ibp_server with these changes on CentOS 7 and Debian unstable.  Seems to work well.  The leveldb parts also compiled without issues.  Merge away.

**Comment by PerilousApricot** [comment]
Cheers.

**Pull request merged**
